[cf-guo]
type = s3
provider = Cloudflare
access_key_id = fe578a75d45581906b712f778821f843
secret_access_key = 77ef43a1d4dfcbc157b6068b79f712a10cf11716c8fa258ef91613c6b9dbdc1e
region = auto
endpoint = https://d6ebbd26dcb367fe5e1fd611d06470e2.r2.cloudflarestorage.com

[safe-encrypted]
type = crypt
remote = cf-guo:guodrive
password = D2j3wcg_ZXjSgpy7JG0996LeW-gwo-LksA

